[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "node src/app.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production"
REDIS_URL = "${REDIS_URL}"
DATABASE_URL = "${DATABASE_URL}"
JWT_SECRET = "${JWT_SECRET}"
MINIO_ENDPOINT = "${MINIO_ENDPOINT}"
MINIO_PORT = "${MINIO_PORT}"
MINIO_ACCESS_KEY = "${MINIO_ACCESS_KEY}"
MINIO_SECRET_KEY = "${MINIO_SECRET_KEY}"
MINIO_BUCKET = "${MINIO_BUCKET}" 