[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "node src/app.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
privateNetworking = true
healthcheckInterval = 30
healthcheckStartPeriod = 60
ssl = true

[deploy.env]
NODE_ENV = "production" 