apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-processor
  template:
    metadata:
      labels:
        app: video-processor
    spec:
      containers:
      - name: video-processor
        image: jrottenberg/ffmpeg:5.1-ubuntu
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 30; done"]  # Keep container running
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: temp-storage
          mountPath: /tmp/videos
      volumes:
      - name: temp-storage
        emptyDir: {}
      tolerations:
      - key: "workload"
        operator: "Equal"
        value: "media"
        effect: "NoSchedule" 